CREATE DATABASE App;
GO

USE App;
GO

CREATE LOGIN AppLogin WITH PASSWORD='AppPassword123', DEFAULT_DATABASE=App;
GO

CREATE USER AppUser FOR LOGIN AppLogin WITH DEFAULT_SCHEMA=dbo;
GO

ALTER ROLE db_owner ADD MEMBER AppUser;
GO
